import React from 'react'

const page = () => {
  return (
    <section className='legalPolicy_sec'>
      <div className='container'>

        <div>
          <p>THIS DOCUMENT CONSTITUTES AN AGREEMENT BETWEEN EITHER YOURSELF OR THE ENTITY YOU REPRESENT (HEREINAFTER REFERRED TO AS "YOU" OR "YOUR") AND “BIZZILO”, GOVERNING YOUR UTILIZATION OF BIZZILO’S SUITE OF ONLINE BUSINESS PRODUCTIVITY AND COLLABORATION SOFTWARE IF YOU ARE SITUATED IN INDIA.</p>

          <h3>Agreement Acceptance:</h3>
          <p>To accept the Agreement, you must be of legal age to enter into a binding contract. If you disagree with the General Terms, refrain from utilizing any of Bizzilo's Services. Acceptance of the Agreement can be demonstrated by checking a checkbox or clicking on a button indicating your agreement, or by actively using the Services.</p>

          <h3>Service Description:</h3>
          <p>We offer cloud software and applications for businesses, including associated offline and mobile applications (referred to as "Service" or "Services"). You may utilize the Services for personal or business use, or for internal business purposes within the organization you represent. Access to the Services is available via any Internet browser supported by the Services. It is your responsibility to procure Internet access and necessary equipment for utilizing the Services. With your user account, you can create, edit, publish, and share content as desired.</p>

          <h3>Beta Service:</h3>
          <p>Certain Services may be provided as closed or open beta services (referred to as "Beta Service" or “Beta Services”) for testing and evaluation purposes. You acknowledge that we have sole authority and discretion to determine the duration of testing and evaluation for Beta Services. Our determination regarding the success of such testing and the decision to offer Beta Services commercially shall be final. Your subscription to any Beta Service does not obligate you to acquire a subscription for any paid Service. We retain the right to wholly or partially discontinue any Beta Services, temporarily or permanently, with or without prior notice to you. You agree that Bizzilo shall not be liable to you or any third party for any harm arising from the modification, suspension, or discontinuation of Beta Services for any reason.</p>

          <h3>Free Plan:</h3>
          <p>Upon registration for a free plan of one or more Services, Bizzilo will grant access to the applicable Services on a trial basis, free of charge, until the earlier of (i) the end of the free trial period, (ii) commencement of the paid subscription period, or (iii) termination by Bizzilo at its discretion. Data entered into the Services and any customizations made during the free trial will be permanently lost unless you (i) purchase the corresponding paid subscription plan, (ii) purchase applicable Service upgrades, or (iii) export such data before the trial period concludes. Services offered during the free trial are provided as-is, without warranty, covenant, support, or liability, to the extent permitted by law.</p>

          <h3>User Registration Obligations:</h3>
          <p>You are required to register for a user account by furnishing all necessary information to access or utilize the Services. If you represent an organization intending to utilize the Services for internal corporate purposes, it is recommended that you, along with other users from your organization, register for user accounts using corporate contact details. Specifically, it is advised to utilize corporate email addresses. By registering, you agree to: (i) provide accurate, current, and complete information about yourself as prompted during registration; and (ii) maintain and promptly update the information provided during registration to ensure its accuracy, currency, and completeness. Should you provide information that is inaccurate, outdated, incomplete, or if Bizzilo has reasonable grounds to suspect the veracity of such information, Bizzilo reserves the right to terminate your user account and deny current or future access to any or all of the Services.</p>

          <h3>Usage Restrictions:</h3>
          <p>In addition to all other terms and conditions outlined in this Agreement, you shall not: (i) transfer the Services or make them available to any third party; (ii) provide any service based on the Services without prior written consent; (iii) permit the sharing or utilization of user licenses by more than one individual, except through the reassignment of the user license to a new user; (iv) unless permitted under applicable law, attempt to disassemble, reverse engineer, or decompile the Services; (v) utilize third-party links to sites without agreeing to their respective website terms and conditions; (vi) post links to third-party sites or utilize their logos, company names, etc., without prior written consent; (vii) attempt to gain unauthorized access to the Services or its associated systems or networks; (viii) utilize the Services in a manner that could damage, disable, overburden, impair, or harm any server, network, computer system, or resource of Bizzilo; (ix) use the Services to transmit or store material containing software viruses, worms, or other harmful computer codes, files, scripts, or programs; (x) utilize the Services in a manner that interferes with or disrupts the integrity, security, or performance of the Services, its components, and the data contained therein; (xi) host, display, upload, modify, publish, transmit, store, update, or share any information belonging to another person or entity without proper authorization, including personal or confidential information; (xii) violate any applicable local, state, national, or international law; (xiii) utilize the Services for competitive or benchmarking purposes; and (xiv) remove or obscure any proprietary or other notices contained in the Services. Additionally, you agree not to use our Services in any manner that jeopardizes the unity, integrity, defense, security, or sovereignty of India, its friendly relations with other countries, public order, incites the commission of a cognizable offense, obstructs the investigation of an offense, insults other countries, creates a false identity to deceive any person regarding the origin of communication, transmits patently false and untrue information with intent to mislead or harass, or encourages activities prohibited by Indian law.</p>

          <h3>Spamming and Illegal Activities:</h3>
          <p>You acknowledge sole responsibility for the contents of your transmissions through the Services. You agree not to utilize the Services for unlawful purposes or for transmitting material that is unlawful, defamatory, libelous, harassing, invasive of privacy, abusive, threatening, harmful, vulgar, pornographic, paedophilic, harmful to children, obscene, racially or ethnically objectionable, offensive to religious sentiments, racist, contains viruses or malicious code, infringes upon intellectual property or other rights, or is otherwise objectionable. You further agree not to use the Services for the transmission of "junk mail", "spam", "chain letters", “phishing”, or unsolicited mass distribution of email. Bizzilo reserves the right to terminate your access to the Services should there be reasonable grounds to believe that you have engaged in illegal or unauthorized activities.</p>

          <h3>Fees and Payment Terms:</h3>
          <p>The Services are accessible via subscription plans offered for various durations. Payments for subscription plans with durations of less than one year are exclusively accepted via Credit Card. Your subscription will automatically renew at the conclusion of each subscription period, unless you choose to downgrade your paid subscription to a free plan or notify us of your intention not to renew the subscription. Upon automatic renewal, the subscription fee will be charged to the Credit Card previously used for payment. You have the option to update payment details if you prefer to utilize a different Credit Card for renewal payment. To avoid subscription renewal, you must notify us at least seven days prior to the renewal date. Failure to downgrade to a free plan or notify us of your non-renewal intention will be construed as authorization for Bizzilo to charge the subscription fee to the Credit Card last used for payment. Please refer to our Refund Policy for further details.</p>

          <p>Periodically, we may adjust the pricing of any Service or introduce charges for Services currently offered free of charge. Any price increases will take effect upon the expiration of your current billing cycle. You will not be charged for the use of any Service unless you have subscribed to a paid subscription plan.</p>

          <p>In the event that Bizzilo is required to levy taxes such as GST, VAT, sales tax, or similar taxes pursuant to local, state, provincial, or foreign laws in relation to your subscription to our Services ("Taxes"), Bizzilo will invoice you for such Taxes. You agree to remit payment for such Taxes in addition to the subscription fees. Bizzilo will furnish you with an invoice in compliance with the format specified by applicable local, state, provincial, or foreign laws to facilitate your access to applicable input tax credits for the Taxes paid.</p>

          <h3><strong>Organization Accounts and Administrators</strong></h3>
          <p>Upon registering an account for your organization, you may designate one or more administrators. These administrators will possess the authority to configure the Services to meet your organization's requirements and oversee end users within your organization account. If a third party creates and configures your organization account on your behalf, it is likely that such third party assumes the role of administrator for your organization. It is imperative that you enter into a suitable agreement with such third parties, delineating their roles and limitations as an administrator of your organization account.</p>

          <p>You are responsible for (i) maintaining the confidentiality of your organization account password, (ii) appointing competent individuals as administrators to manage your organization account, and (iii) ensuring that all activities associated with your organization account comply with this Agreement. You acknowledge that Bizzilo is not accountable for account administration or internal management of the Services on your behalf.</p>

          <p>It is your responsibility to take necessary measures to prevent loss of control over administrator accounts within your organization. You may establish a procedure for recovering control in the event of such loss by submitting a request via email to <a href="mailto:legal@bizzilo.com">legal@bizzilo.com</a>, provided that the proposed process is acceptable to Bizzilo. In the absence of a specified administrator account recovery procedure, Bizzilo may grant control of an administrator account to an individual providing satisfactory proof of authorization to act on behalf of the organization. You agree not to hold Bizzilo liable for any consequences arising from actions taken in good faith by Bizzilo in this regard.</p>

          <h3><strong>Personal Information and Privacy</strong></h3>
          <p>Any personal information you provide to Bizzilo through the Service is governed by Bizzilo's Privacy Policy. Your decision to utilize the Service signifies your acceptance of the terms outlined in Bizzilo's Privacy Policy. You are accountable for safeguarding the confidentiality of your username, password, and other sensitive information. Furthermore, you are responsible for all activities conducted within your user account, and you agree to promptly notify us of any unauthorized use of your user account via email to <a href="mailto:support@bizzilo.com">support@bizzilo.com</a>. Bizzilo disclaims any responsibility for any loss or damage incurred by you or any third party as a result of unauthorized access and/or use of your user account or otherwise.</p>

          <h3><strong>Communications from Bizzilo</strong></h3>
          <p>The Service may include certain communications from Bizzilo, such as service announcements, administrative messages, and newsletters. You acknowledge that these communications are integral to the use of the Services. In adherence to our privacy policy, we provide you with the option to opt out of receiving newsletters. However, opting out of newsletters does not apply to service announcements and administrative messages, which you will continue to receive.</p>

          <h3><strong>Complaints</strong></h3>
          <p>In the event that we receive a complaint regarding your activities while using the Services (excluding complaints addressed under the "Grievance Redressal" mechanism), we will forward the complaint to the primary email address associated with your user account. You are required to directly respond to the complainant within 10 days of receiving the forwarded complaint from us and copy Bizzilo in the communication. Failure to respond to the complainant within the specified 10-day timeframe may result in the disclosure of your name and contact information to the complainant, enabling them to pursue legal action against you. You acknowledge that your failure to respond within the designated timeframe constitutes consent for Bizzilo to disclose your name and contact information to the complainant.</p>

          <h3><strong>Grievance Redressal</strong></h3>
          <p>Should you have any grievances, as defined under the Information Technology (Intermediary Guidelines and Digital Media Ethics Code) Rules 2021, you may contact our Grievance Officer, by sending an email to <a href="mailto:support@bizzilo.com">support@bizzilo.com</a>.</p>

          <h3><strong>Inactive User Accounts Policy</strong></h3>
          <p>We retain the authority to terminate unpaid user accounts that remain inactive for a continuous period of 120 days. Upon such termination, all data associated with the user account will be permanently deleted. Prior notice of termination will be provided, along with the option to back up your data. The data deletion policy may be enforced for any or all of the Services offered. Each Service is regarded as an independent entity for calculating the period of inactivity. Activity within one Service does not suffice to maintain the active status of your user account in another Service. In cases where an account has multiple users, if at least one user remains active, the account will not be classified as inactive.</p>

          <h3><strong>Hosting Location</strong></h3>
          <p>The geographical location of the cloud facility serving you is contingent upon the mapping of your region/country to available cloud facilities at the time of your account registration. We reserve the right to migrate your account or request you to migrate to a different cloud facility should updates occur in the region/country to cloud facility mapping. It is imperative that you do not mask your internet protocol (IP) address during registration, as your region/country is determined based on your IP address. If, at any point, your actual region/country is found to be different from the region/country in our records, appropriate actions, such as account migration or closure, may be taken by Bizzilo to align your account with the correct region/country. If you are served from a cloud facility outside your region/country and a Bizzilo group entity maintains an office in your region/country, in addition to storing data in the assigned cloud facility, we may also retain a local copy of your data within your region/country.</p>

          <h3><strong>Data Ownership</strong></h3>
          <p>We respect your ownership rights over content created or stored by you. Unless expressly permitted by you, our provision of the Services does not confer upon Bizzilo the license to utilize, reproduce, adapt, modify, publish, or distribute the content created or stored by you for commercial, marketing, or similar purposes. However, you grant Bizzilo permission to access, copy, distribute, store, transmit, reformat, publicly display, and publicly perform the content of your user account solely for the purpose of providing the Services to you.</p>

          <h3><strong>User Generated Content</strong></h3>
          <p>You may transmit or publish content created by you using any of the Services. However, you bear sole responsibility for such content and its consequences. If you publish news and current affairs content as defined under the Information Technology (Intermediary Guidelines and Digital Media Ethics Code) Rules 2021, you must furnish details to the Ministry of Information and Broadcasting as mandated by rule 18. Any content made public will be accessible through the internet and may be indexed by search engines. You must ensure that private content remains private to avoid inadvertent public access. Content received from other users is provided for your personal use only, and you agree not to exploit such content without express written consent from the content owner. You also agree not to remove copyright notices or disable copy protection features from copyrighted content. By making copyrighted content available, you affirm that you have the necessary consent, authorization, or permission from relevant parties. Furthermore, you consent to Bizzilo's right to block access to or remove such content if complaints arise regarding illegality or infringement of third-party rights. You also consent to Bizzilo's designated agent determining questions of illegality or infringement of third-party rights in such content.</p>

          <h3><strong>Sample Files and Applications</strong></h3>
          <p>Bizzilo may furnish sample files and applications to showcase the potential use of the Services effectively for specific purposes. The content within these sample files and applications comprises random data. Bizzilo provides no warranty, either express or implied, regarding the accuracy, utility, comprehensiveness, or reliability of the information or the sample files and applications.</p>

          <h3><strong>Trademark</strong></h3>
          <p><strong>Bizzilo, Bizzilo logo, the names of individual Services, and their logos are trademarks of Bizzilo Corporation Private Limited. You agree not to exhibit or utilize, in any manner, the Bizzilo trademarks, without prior permission from Bizzilo.</strong></p>

          <h3>Disclaimer of Warranties</h3>
          <p>YOU EXPRESSLY UNDERSTAND AND AGREE THAT THE UTILIZATION OF THE SERVICES IS SOLELY AT YOUR OWN RISK. THE SERVICES ARE PROVIDED ON AN "AS-IS" AND "AS-AVAILABLE" BASIS. BIZZILO EXPRESSLY DISCLAIMS ALL WARRANTIES OF ANY KIND, WHETHER EXPRESS OR IMPLIED, INCLUDING, BUT NOT LIMITED TO, THE IMPLIED WARRANTIES OF MERCHANTABILITY AND FITNESS FOR A PARTICULAR PURPOSE. BIZZILO MAKES NO WARRANTY THAT THE SERVICES WILL BE UNINTERRUPTED, TIMELY, SECURE, OR ERROR-FREE. THE USE OF ANY MATERIAL DOWNLOADED OR OBTAINED THROUGH THE SERVICES SHALL BE AT YOUR SOLE DISCRETION AND RISK, AND YOU SHALL BE SOLELY RESPONSIBLE FOR ANY DAMAGE TO YOUR COMPUTER SYSTEM, MOBILE TELEPHONE, WIRELESS DEVICE, OR DATA THAT RESULTS FROM SUCH USE OF THE SERVICES OR THE DOWNLOAD OF ANY SUCH MATERIAL. NO ADVICE OR INFORMATION, WHETHER WRITTEN OR ORAL, OBTAINED BY YOU FROM BIZZILO, ITS EMPLOYEES, OR REPRESENTATIVES SHALL CREATE ANY WARRANTY NOT EXPRESSLY STATED IN THE AGREEMENT.</p>

          <h3>Limitation of Liability</h3>
          <p>YOU AGREE THAT BIZZILO SHALL NOT, UNDER ANY CIRCUMSTANCES, BE LIABLE FOR ANY CONSEQUENTIAL, INCIDENTAL, INDIRECT, SPECIAL, PUNITIVE, OR OTHER LOSS OR DAMAGE WHATSOEVER, INCLUDING BUT NOT LIMITED TO LOSS OF BUSINESS PROFITS, BUSINESS INTERRUPTION, COMPUTER FAILURE, LOSS OF BUSINESS INFORMATION, OR ANY OTHER LOSS ARISING OUT OF OR CAUSED BY YOUR USE OF OR INABILITY TO USE THE SERVICE, EVEN IF BIZZILO HAS BEEN ADVISED OF THE POSSIBILITY OF SUCH DAMAGE. IN NO EVENT SHALL BIZZILO'S ENTIRE LIABILITY TO YOU IN RESPECT OF ANY SERVICE, WHETHER DIRECT OR INDIRECT, EXCEED FIFTY THOUSAND RUPEES (₹ 10,000) OR THE FEES PAID BY YOU DURING THE TWELVE (6) MONTHS PRIOR TO THE FIRST EVENT GIVING RISE TO SUCH LIABILITY, WHICHEVER IS HIGHER.</p>

          <h3>Indemnification</h3>
          <p>You agree to indemnify and hold harmless Bizzilo, its officers, directors, employees, suppliers, and affiliates, from and against any losses, damages, fines, and expenses (including attorney's fees and costs) arising out of or relating to any claims that you have used the Services in violation of another party's rights, in violation of any law, in violation of any provisions of the Agreement, or any other claim related to your use of the Services, except where such use is authorized by Bizzilo.</p>

          <h3>Governing Law and Jurisdiction</h3>
          <p>Any dispute or claim arising out of or relating to the Terms shall be settled and adjudicated exclusively by the courts of Chennai in accordance with the laws of India, without regard to conflict of law principles.</p>

          <h3>Suspension and Termination</h3>
          <p>Bizzilo reserves the right to suspend your user account or temporarily disable access to whole or part of any Service if there is suspicion of illegal activity, prolonged periods of inactivity, or upon requests by law enforcement or other government agencies. Any objections to the suspension or disabling of user accounts should be addressed to legal@bizzilo.com within thirty days of receiving notification about the suspension. Bizzilo may terminate a suspended or disabled user account after the expiration of thirty days. Additionally, Bizzilo reserves the right to terminate your user account and deny access to the Services if there is reasonable belief that you have breached the Agreement. Bizzilo also reserves the right to terminate access to any Beta Service in the event of unexpected technical issues or discontinuation of the Beta Service. You have the right to terminate your user account if Bizzilo breaches its obligations under this Agreement, and in such event, you will be entitled to a prorated refund of any prepaid fees. Termination of a user account will result in the denial of access to all Services, deletion of user account information, such as email address and password, and deletion of all data within the user account.</p>

          <h3>Modification of Terms of Service</h3>
          <p>Bizzilo may modify this Agreement with notice to you at any time through a service announcement or by sending an email to your primary email address. If significant changes are made to the Agreement that affect your rights, you will <strong>receive at least 30 days advance notice</strong> of the changes via email to your primary email address. You may terminate your use of the Services by providing notice to Bizzilo via email <strong>within 30 days</strong> of being notified of the availability of the modified Agreement if the modifications substantially affect your rights in connection with the use of the Services. In the event of such termination, you will be entitled to a prorated refund of the unused portion of any prepaid fees. Your continued use of the Service after the effective date of any change to the Agreement will be deemed as your agreement to the modified Agreement.</p>

          <h3>End Of Terms Of Service</h3>
          <p>For any questions or concerns regarding this Agreement, please contact us at <a href="mailto:legal@bizzilo.com">legal@bizzilo.com</a>.</p>

          <h3><strong>Usage Limits for Modules or corresponding Application Programming Interfaces (APIs)</strong></h3>
          <p>Bizzilo reserves the right to establish usage limits, which may include restrictions on the number of API calls, number of records per call, bandwidth consumption, and frequency of calls. It is incumbent upon you to comply with the usage limits set forth by Bizzilo to ensure uninterrupted access to services. You acknowledge that Bizzilo may curtail certain activities upon reaching the prescribed usage limit associated with such activities. Furthermore, it is understood that an API call may fail entirely or be only partially executed should the usage limits be exceeded prior to or during the execution of said call.</p>



          <p><strong>iv. Testimonials:</strong> If you authorize us to post testimonials about our products and services on websites, we may include your name and other personal information in the testimonial. Before posting, you'll have the opportunity to review and approve the testimonial. If you wish to update or delete your testimonial, you can contact us at <a href="mailto:privacy@bizzilo.com">privacy@bizzilo.com</a>.</p>



          <h3>Purposes for utilizing information:</h3>

          <p>Apart from the previously mentioned purposes, we may utilize your information for the following:</p>



          <h3>Notification of Policy Changes:</h3>

          <p>We reserve the right to modify this Privacy Policy at any time, with notification provided through service announcements or email to your primary email address. Significant changes affecting your rights will be communicated at least 30 days in advance of the changes taking effect. However, if you have not verified your email address, you may miss important notifications sent via email. If you believe that the updated Privacy Policy affects your rights concerning the use of our products or services, you may terminate your use by notifying us via email within 30 days. Continued use of our products or services after the effective date of changes to the Privacy Policy will constitute your agreement to the modified policy. Minor changes to the Privacy Policy will not trigger email notifications. If you have concerns about the use of your personal information, we recommend periodically reviewing <a href="/privacy-policy">privacy policy</a>.</p>

        </div>
      </div>
    </section>
  )
}

export default page
