import { Geist, Geist_Mono } from "next/font/google";
import "../style.scss";
import Providers from "../../components/Providers";

import "bootstrap/dist/css/bootstrap.min.css";
import Header from "../../components/Layout/Header";
import Footer from "../../components/Layout/Footer";



const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={`${geistSans.variable} ${geistMono.variable}`}>
        <Header />
        <Providers>{children}</Providers>
        <Footer />
      </body>
    </html>
  );
}
